//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.MediatR.Sources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.MediatR.Sources.SourceErrors", typeof(SourceErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is required..
        /// </summary>
        internal static string CreateSourceLinkCategoryCommandValidatorImageIsRequiredError {
            get {
                return ResourceManager.GetString("CreateSourceLinkCategoryCommandValidatorImageIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetcoeId is required..
        /// </summary>
        internal static string CreateSourceLinkCategoryCommandValidatorStreetcodeIdeIsRequiredError {
            get {
                return ResourceManager.GetString("CreateSourceLinkCategoryCommandValidatorStreetcodeIdeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string CreateSourceLinkCategoryCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("CreateSourceLinkCategoryCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateSourceLinkCategoryCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("CreateSourceLinkCategoryCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to SourceLinkCategory..
        /// </summary>
        internal static string CreateSourceLinkCategoryHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("CreateSourceLinkCategoryHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a SourceLinkCategory..
        /// </summary>
        internal static string CreateSourceLinkCategoryHandlerFailedToCreateError {
            get {
                return ResourceManager.GetString("CreateSourceLinkCategoryHandlerFailedToCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateStreetcodeCategoryContentCommandTextLengthMaxLengthError {
            get {
                return ResourceManager.GetString("CreateStreetcodeCategoryContentCommandTextLengthMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLinkId is required..
        /// </summary>
        internal static string CreateStreetcodeCategoryContentCommandValidatorSourceLinkIdIsRequiredError {
            get {
                return ResourceManager.GetString("CreateStreetcodeCategoryContentCommandValidatorSourceLinkIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetcoeId is required..
        /// </summary>
        internal static string CreateStreetcodeCategoryContentCommandValidatorStreetcodeIdIsRequiredError {
            get {
                return ResourceManager.GetString("CreateStreetcodeCategoryContentCommandValidatorStreetcodeIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from null.
        /// </summary>
        internal static string CreateStreetcodeCategoryContentHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("CreateStreetcodeCategoryContentHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a StreetcodeCategoryContent.
        /// </summary>
        internal static string CreateStreetcodeCategoryContentHandlerFailedToCreateError {
            get {
                return ResourceManager.GetString("CreateStreetcodeCategoryContentHandlerFailedToCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SourceLinkCategory found by entered Id - {0}..
        /// </summary>
        internal static string DeleteSourceLinkCategoryHandlerCanNotFindSourceLinkCategoryWithGivenIdError {
            get {
                return ResourceManager.GetString("DeleteSourceLinkCategoryHandlerCanNotFindSourceLinkCategoryWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete SourceLinkCaategory.
        /// </summary>
        internal static string DeleteSourceLinkCategoryHandlerFailedToDeleteError {
            get {
                return ResourceManager.GetString("DeleteSourceLinkCategoryHandlerFailedToDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No StreetcodeCategoryContent found by entered Id - {0}..
        /// </summary>
        internal static string DeleteStreetcodeCategoryContentHandlerCanNotFindStreetcodeCategoryContentWithGivenIdError {
            get {
                return ResourceManager.GetString("DeleteStreetcodeCategoryContentHandlerCanNotFindStreetcodeCategoryContentWithGive" +
                        "nIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete StreetcodeCategoryContent.
        /// </summary>
        internal static string DeleteStreetcodeCategoryContentHandlerFailedToDeleteError {
            get {
                return ResourceManager.GetString("DeleteStreetcodeCategoryContentHandlerFailedToDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories are null.
        /// </summary>
        internal static string GetAllCategoriesHandlerCategoriesAreNullError {
            get {
                return ResourceManager.GetString("GetAllCategoriesHandlerCategoriesAreNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streetcode content is null.
        /// </summary>
        internal static string GetAllCategoryContentsBySteetcodeIdAndSourceLinkCategoryIdHandlerStreetcodeIsNullError {
            get {
                return ResourceManager.GetString("GetAllCategoryContentsBySteetcodeIdAndSourceLinkCategoryIdHandlerStreetcodeIsNull" +
                        "Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such streetcode with id - {0}.
        /// </summary>
        internal static string GetAllCategoryContentsBySteetcodeIdAndSourceLinkCategoryIdHandlerWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetAllCategoryContentsBySteetcodeIdAndSourceLinkCategoryIdHandlerWithGivenStreetc" +
                        "odeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories are null.
        /// </summary>
        internal static string GetAllCategoryNamesHandlerCategoriesAreNullError {
            get {
                return ResourceManager.GetString("GetAllCategoryNamesHandlerCategoriesAreNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no SourceLinkCategory in the database..
        /// </summary>
        internal static string GetAllSourceLinkCategoryHandlerCanNotFindAnySourceLinkCategoryError {
            get {
                return ResourceManager.GetString("GetAllSourceLinkCategoryHandlerCanNotFindAnySourceLinkCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant find any source category with the streetcode id - {0}.
        /// </summary>
        internal static string GetCategoriesContentByStreetcodeIdHandlerWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetCategoriesContentByStreetcodeIdHandlerWithGivenStreetcodeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SourceLinkCategory by entered Id - {0}..
        /// </summary>
        internal static string GetSourceLinkCategoryByIdHandlerCanNotFindANewWithGivenIdError {
            get {
                return ResourceManager.GetString("GetSourceLinkCategoryByIdHandlerCanNotFindANewWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant find any source category with the streetcode - {0}..
        /// </summary>
        internal static string GetSourceLinkCategoryByIdHandlerCanNotFindAWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetSourceLinkCategoryByIdHandlerCanNotFindAWithGivenStreetcodeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streetcode content is null.
        /// </summary>
        internal static string GetSourceLinkCategoryContentHandlerStreetcodeContentIsNullError {
            get {
                return ResourceManager.GetString("GetSourceLinkCategoryContentHandlerStreetcodeContentIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLinkId is required..
        /// </summary>
        internal static string UpdateSourceLinkCategoryCommandValidatorSourceLinkIdeIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateSourceLinkCategoryCommandValidatorSourceLinkIdeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetcoeId is required..
        /// </summary>
        internal static string UpdateSourceLinkCategoryCommandValidatorStreetcodeIdeIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateSourceLinkCategoryCommandValidatorStreetcodeIdeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string UpdateSourceLinkCategoryCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateSourceLinkCategoryCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateSourceLinkCategoryCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateSourceLinkCategoryCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to SourceLinkCategory..
        /// </summary>
        internal static string UpdateSourceLinkCategoryHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("UpdateSourceLinkCategoryHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update SourceLinkCategory.
        /// </summary>
        internal static string UpdateSourceLinkCategoryHandlerFailedToUpdateError {
            get {
                return ResourceManager.GetString("UpdateSourceLinkCategoryHandlerFailedToUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant find any image with the ImageId - {0}.
        /// </summary>
        internal static string UpdateSourceLinkHandlerCanNotFindImageWithGivenIdError {
            get {
                return ResourceManager.GetString("UpdateSourceLinkHandlerCanNotFindImageWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text length should not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateStreetcodeCategoryContentCommandTextLengthMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateStreetcodeCategoryContentCommandTextLengthMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLinkId is required..
        /// </summary>
        internal static string UpdateStreetcodeCategoryContentCommandValidatorSourceLinkIdIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateStreetcodeCategoryContentCommandValidatorSourceLinkIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetcoeId is required..
        /// </summary>
        internal static string UpdateStreetcodeCategoryContentCommandValidatorStreetcodeIdIsRequired {
            get {
                return ResourceManager.GetString("UpdateStreetcodeCategoryContentCommandValidatorStreetcodeIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text length should not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateStreetcodeCategoryContentCommandValidatorTextMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateStreetcodeCategoryContentCommandValidatorTextMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to StreetcodeCategoryContent.
        /// </summary>
        internal static string UpdateStreetcodeCategoryContentHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("UpdateStreetcodeCategoryContentHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update StreetcodeCategoryContent.
        /// </summary>
        internal static string UpdateStreetcodeCategoryContentHandlerFailedToUpdateError {
            get {
                return ResourceManager.GetString("UpdateStreetcodeCategoryContentHandlerFailedToUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SourceLinkCategory found by entered Id - {0}..
        /// </summary>
        internal static string UpdateStreetcodeCategoryHandlerCanNotFindSourceLinkCategoryWithGivenIdError {
            get {
                return ResourceManager.GetString("UpdateStreetcodeCategoryHandlerCanNotFindSourceLinkCategoryWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Streetcode found by entered Id - {0}..
        /// </summary>
        internal static string UpdateStreetcodeCategoryHandlerCanNotFindStreetcodeWithGivenIdError {
            get {
                return ResourceManager.GetString("UpdateStreetcodeCategoryHandlerCanNotFindStreetcodeWithGivenIdError", resourceCulture);
            }
        }
    }
}
