//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.MediatR.Streetcode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StreetcodeErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StreetcodeErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.MediatR.Streetcode.StreetcodeErrors", typeof(StreetcodeErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Content length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateFactCommandValidatorFactContentMaxLengthError {
            get {
                return ResourceManager.GetString("CreateFactCommandValidatorFactContentMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Content is required..
        /// </summary>
        internal static string CreateFactCommandValidatorFactIsRequiredError {
            get {
                return ResourceManager.GetString("CreateFactCommandValidatorFactIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string CreateFactCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("CreateFactCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateFactCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("CreateFactCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to fact..
        /// </summary>
        internal static string CreateFactHandlerCannotConvertNullToFactError {
            get {
                return ResourceManager.GetString("CreateFactHandlerCannotConvertNullToFactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a fact..
        /// </summary>
        internal static string CreateFactHandlerFailedToCreateFactError {
            get {
                return ResourceManager.GetString("CreateFactHandlerFailedToCreateFactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image with id {0} does not exist..
        /// </summary>
        internal static string CreateFactHandlerImageWithIdDoesNotExistError {
            get {
                return ResourceManager.GetString("CreateFactHandlerImageWithIdDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streetcode with id {0} does not exist..
        /// </summary>
        internal static string CreateFactHandlerStreetcodeWithIdDoesNotExistError {
            get {
                return ResourceManager.GetString("CreateFactHandlerStreetcodeWithIdDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a relation..
        /// </summary>
        internal static string CreateRelatedFigureHandlerFailedToCreateRelationError {
            get {
                return ResourceManager.GetString("CreateRelatedFigureHandlerFailedToCreateRelationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existing streetcode with id: {0}.
        /// </summary>
        internal static string CreateRelatedFigureHandlerNoExistingStreetcodeWithIdError {
            get {
                return ResourceManager.GetString("CreateRelatedFigureHandlerNoExistingStreetcodeWithIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Id is required..
        /// </summary>
        internal static string CreateRelatedFigureValidatorObserverIdIsRequiredError {
            get {
                return ResourceManager.GetString("CreateRelatedFigureValidatorObserverIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Id is required..
        /// </summary>
        internal static string CreateRelatedFigureValidatorTargetIdIsRequiredError {
            get {
                return ResourceManager.GetString("CreateRelatedFigureValidatorTargetIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create new related word for a term!.
        /// </summary>
        internal static string CreateRelatedTermHandlerCannotCreateNewRelatedWordForTermError {
            get {
                return ResourceManager.GetString("CreateRelatedTermHandlerCannotCreateNewRelatedWordForTermError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map entity!.
        /// </summary>
        internal static string CreateRelatedTermHandlerCannotMapEntityError {
            get {
                return ResourceManager.GetString("CreateRelatedTermHandlerCannotMapEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save changes in the database after related word creation!.
        /// </summary>
        internal static string CreateRelatedTermHandlerCannotSaveChangesInDatabaseAfterRelatedWordCreationError {
            get {
                return ResourceManager.GetString("CreateRelatedTermHandlerCannotSaveChangesInDatabaseAfterRelatedWordCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateRelatedTermHandlerMaxWordLengthError {
            get {
                return ResourceManager.GetString("CreateRelatedTermHandlerMaxWordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Id is required..
        /// </summary>
        internal static string CreateRelatedTermHandlerTermIdIsRequiredError {
            get {
                return ResourceManager.GetString("CreateRelatedTermHandlerTermIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word is required..
        /// </summary>
        internal static string CreateRelatedTermHandlerWordIsRequiredError {
            get {
                return ResourceManager.GetString("CreateRelatedTermHandlerWordIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово з цим визначенням уже існує..
        /// </summary>
        internal static string CreateRelatedTermHandlerWordWithThisDefinitionAlreadyExistsError {
            get {
                return ResourceManager.GetString("CreateRelatedTermHandlerWordWithThisDefinitionAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete fact..
        /// </summary>
        internal static string DeleteFactHandlerFailedToDeleteError {
            get {
                return ResourceManager.GetString("DeleteFactHandlerFailedToDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fact found by entered Id - {0}..
        /// </summary>
        internal static string DeleteFactHandlerNoFactFoundByEnteredIdError {
            get {
                return ResourceManager.GetString("DeleteFactHandlerNoFactFoundByEnteredIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a relation between streetcodes with corresponding ids: {0} {1}..
        /// </summary>
        internal static string DeleteRelatedFigureHandlerCannotFindRelationBetweenStreetcodesWithCorrespondingIdsError {
            get {
                return ResourceManager.GetString("DeleteRelatedFigureHandlerCannotFindRelationBetweenStreetcodesWithCorrespondingId" +
                        "sError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a relation..
        /// </summary>
        internal static string DeleteRelatedFigureHandlerFailedToDeleteError {
            get {
                return ResourceManager.GetString("DeleteRelatedFigureHandlerFailedToDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a related term: {0}..
        /// </summary>
        internal static string DeleteRelatedTermHandlerCannotFindRelatedTermError {
            get {
                return ResourceManager.GetString("DeleteRelatedTermHandlerCannotFindRelatedTermError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a related term..
        /// </summary>
        internal static string DeleteRelatedTermHandlerFailedToDeleteRelatedTermError {
            get {
                return ResourceManager.GetString("DeleteRelatedTermHandlerFailedToDeleteRelatedTermError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a streetcode with corresponding categoryId: {0}..
        /// </summary>
        internal static string DeleteSoftStreetcodeHandlerCannotFindStreetcodeWithCorrespondingIdError {
            get {
                return ResourceManager.GetString("DeleteSoftStreetcodeHandlerCannotFindStreetcodeWithCorrespondingIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change status of streetcode to deleted..
        /// </summary>
        internal static string DeleteSoftStreetcodeHandlerFailedToChangeStatusOfStreetcodeToDeletedError {
            get {
                return ResourceManager.GetString("DeleteSoftStreetcodeHandlerFailedToChangeStatusOfStreetcodeToDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any fact..
        /// </summary>
        internal static string GetAllFactsHandlerCanNotFindAnyFactsError {
            get {
                return ResourceManager.GetString("GetAllFactsHandlerCanNotFindAnyFactsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create DTOs for related words!.
        /// </summary>
        internal static string GetAllRelatedTermsByTermIdHandlerCannotCreateDtosForRelatedWordsError {
            get {
                return ResourceManager.GetString("GetAllRelatedTermsByTermIdHandlerCannotCreateDtosForRelatedWordsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get words by term id..
        /// </summary>
        internal static string GetAllRelatedTermsByTermIdHandlerCannotGetWordsByTermIdError {
            get {
                return ResourceManager.GetString("GetAllRelatedTermsByTermIdHandlerCannotGetWordsByTermIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any subtitles..
        /// </summary>
        internal static string GetAllStreetcodesCatalogHandlerCannotFindAnySubtitlesError {
            get {
                return ResourceManager.GetString("GetAllStreetcodesCatalogHandlerCannotFindAnySubtitlesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No streetcodes exist now..
        /// </summary>
        internal static string GetAllStreetcodesMainPageHandlerNoStreetcodesExistNowError {
            get {
                return ResourceManager.GetString("GetAllStreetcodesMainPageHandlerNoStreetcodesExistNowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No streetcodes exist now..
        /// </summary>
        internal static string GetAllStreetcodesShortHandlerNoStreetcodesExistNowError {
            get {
                return ResourceManager.GetString("GetAllStreetcodesShortHandlerNoStreetcodesExistNowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any term..
        /// </summary>
        internal static string GetAllTermsHandlerCannotFindAnyTermError {
            get {
                return ResourceManager.GetString("GetAllTermsHandlerCannotFindAnyTermError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any text..
        /// </summary>
        internal static string GetAllTextsHandlerCannotFindAnyTextError {
            get {
                return ResourceManager.GetString("GetAllTextsHandlerCannotFindAnyTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot find any fact with corresponding id: {0}..
        /// </summary>
        internal static string GetFactByIdCannotFindAnyFactWithCorrespondingIdError {
            get {
                return ResourceManager.GetString("GetFactByIdCannotFindAnyFactWithCorrespondingIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any fact by the streetcode id: {0}..
        /// </summary>
        internal static string GetFactByStreetcodeHandlerCanNotFindFactWithGivenStreetcodeError {
            get {
                return ResourceManager.GetString("GetFactByStreetcodeHandlerCanNotFindFactWithGivenStreetcodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text was not parsed successfully..
        /// </summary>
        internal static string GetParsedTextAdminPreviewHandlerTextWasNotParsedSuccessfullyError {
            get {
                return ResourceManager.GetString("GetParsedTextAdminPreviewHandlerTextWasNotParsedSuccessfullyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any related figures by a streetcode id: {0}..
        /// </summary>
        internal static string GetRelatedFigureByStreetcodeIdHandlerCannotFindAnyRelatedFigureByStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetRelatedFigureByStreetcodeIdHandlerCannotFindAnyRelatedFigureByStreetcodeIdErro" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding tagid: {0}.
        /// </summary>
        internal static string GetRelatedFigureByTagIdHandlerCannotFindAnyStreetcodeWithcorrespondingTagIdError {
            get {
                return ResourceManager.GetString("GetRelatedFigureByTagIdHandlerCannotFindAnyStreetcodeWithcorrespondingTagIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding id: {0}.
        /// </summary>
        internal static string GetStreetcodeByIdHandlerCannotFindAnyStreetcodeWithCorrespondingIdError {
            get {
                return ResourceManager.GetString("GetStreetcodeByIdHandlerCannotFindAnyStreetcodeWithCorrespondingIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding index: {0}.
        /// </summary>
        internal static string GetStreetcodeByIndexHandlerCannotFindAnyStreetcodeWithCorrespondingIndexError {
            get {
                return ResourceManager.GetString("GetStreetcodeByIndexHandlerCannotFindAnyStreetcodeWithCorrespondingIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by transliteration url: {0}.
        /// </summary>
        internal static string GetStreetcodeByTransliterationUrlHandlerCannotFindStreetcodeByTransliterationUrlError {
            get {
                return ResourceManager.GetString("GetStreetcodeByTransliterationUrlHandlerCannotFindStreetcodeByTransliterationUrlE" +
                        "rror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No streetcodes exist now..
        /// </summary>
        internal static string GetStreetcodesCountHandlerNoStreetcodesExistNowError {
            get {
                return ResourceManager.GetString("GetStreetcodesCountHandlerNoStreetcodesExistNowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find streetcode by id..
        /// </summary>
        internal static string GetStreetcodeShortByIdHandlerCannotFindStreetcodeByIdError {
            get {
                return ResourceManager.GetString("GetStreetcodeShortByIdHandlerCannotFindStreetcodeByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map streetcode to shortDTO..
        /// </summary>
        internal static string GetStreetcodeShortByIdHandlerCannotMapStreetcodeToShortDtoError {
            get {
                return ResourceManager.GetString("GetStreetcodeShortByIdHandlerCannotMapStreetcodeToShortDtoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any term with corresponding id: {0}.
        /// </summary>
        internal static string GetTermByIdHandlerCannotFindAnyTermWithCorrespondingIdError {
            get {
                return ResourceManager.GetString("GetTermByIdHandlerCannotFindAnyTermWithCorrespondingIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any text with corresponding id: {0}.
        /// </summary>
        internal static string GetTextByIdHandlerCannotFindAnyTextWithCorrespondingIdError {
            get {
                return ResourceManager.GetString("GetTextByIdHandlerCannotFindAnyTextWithCorrespondingIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a transaction link by a streetcode id: {0}, because such streetcode doesn`t exist.
        /// </summary>
        internal static string GetTextByStreetcodeIdHandlerCannotFindTransactionLinkByStreetcodeThisStreetcodeDoesNotExistError {
            get {
                return ResourceManager.GetString("GetTextByStreetcodeIdHandlerCannotFindTransactionLinkByStreetcodeThisStreetcodeDo" +
                        "esNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any fact by the streetcode id: {0}..
        /// </summary>
        internal static string ResetFactOrderHandlerCannotFindAnyFactByStreetcodeIdError {
            get {
                return ResourceManager.GetString("ResetFactOrderHandlerCannotFindAnyFactByStreetcodeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset order numbers..
        /// </summary>
        internal static string ResetFactOrderHandlerFailedToResetOrderNumbersError {
            get {
                return ResourceManager.GetString("ResetFactOrderHandlerFailedToResetOrderNumbersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set order numbers..
        /// </summary>
        internal static string ResetFactOrderHandlerFailedToSetOrderNumbersError {
            get {
                return ResourceManager.GetString("ResetFactOrderHandlerFailedToSetOrderNumbersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Content length should not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateFactCommandValidatorFactContentMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateFactCommandValidatorFactContentMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Content is required..
        /// </summary>
        internal static string UpdateFactCommandValidatorFactIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateFactCommandValidatorFactIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string UpdateFactCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateFactCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateFactCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateFactCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to fact..
        /// </summary>
        internal static string UpdateFactHandlerCannotConvertNullToFactError {
            get {
                return ResourceManager.GetString("UpdateFactHandlerCannotConvertNullToFactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fact with id {request.Fact.Id} does not exist..
        /// </summary>
        internal static string UpdateFactHandlerFactWithIdDoesNotExistError {
            get {
                return ResourceManager.GetString("UpdateFactHandlerFactWithIdDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update fact..
        /// </summary>
        internal static string UpdateFactHandlerFailedToUpdateError {
            get {
                return ResourceManager.GetString("UpdateFactHandlerFailedToUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image with id {0} does not exist..
        /// </summary>
        internal static string UpdateFactHandlerImageWithIdDoesNotExistError {
            get {
                return ResourceManager.GetString("UpdateFactHandlerImageWithIdDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streetcode with id {0} does not exist..
        /// </summary>
        internal static string UpdateFactHandlerStreetcodeWithIdDoesNotExistError {
            get {
                return ResourceManager.GetString("UpdateFactHandlerStreetcodeWithIdDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word length should not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateRelatedTermHandlerMaxWordLengthError {
            get {
                return ResourceManager.GetString("UpdateRelatedTermHandlerMaxWordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Id is required..
        /// </summary>
        internal static string UpdateRelatedTermHandlerTermIdIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateRelatedTermHandlerTermIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word is required..
        /// </summary>
        internal static string UpdateRelatedTermHandlerWordIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateRelatedTermHandlerWordIsRequiredError", resourceCulture);
            }
        }
    }
}
