//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.MediatR.Media {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MediaErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.MediatR.Media.MediaErrors", typeof(MediaErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob Name is required..
        /// </summary>
        internal static string CreateAudioCommandValidatorBlobNameIsRequiredError {
            get {
                return ResourceManager.GetString("CreateAudioCommandValidatorBlobNameIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob Name length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateAudioCommandValidatorBlobNameMaxLengthError {
            get {
                return ResourceManager.GetString("CreateAudioCommandValidatorBlobNameMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string CreateAudioCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("CreateAudioCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateAudioCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("CreateAudioCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an audio..
        /// </summary>
        internal static string CreateAudioHandlerFailedToCreateAnAudioError {
            get {
                return ResourceManager.GetString("CreateAudioHandlerFailedToCreateAnAudioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateImageCommandValidatorAltMaxLengthError {
            get {
                return ResourceManager.GetString("CreateImageCommandValidatorAltMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mime Type is required..
        /// </summary>
        internal static string CreateImageCommandValidatorMimeTypeIsRequiredError {
            get {
                return ResourceManager.GetString("CreateImageCommandValidatorMimeTypeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mime Type length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateImageCommandValidatorMimeTypeMaxLengthError {
            get {
                return ResourceManager.GetString("CreateImageCommandValidatorMimeTypeMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateImageCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("CreateImageCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an image..
        /// </summary>
        internal static string CreateImageHandlerFailedToCreateAnAudioError {
            get {
                return ResourceManager.GetString("CreateImageHandlerFailedToCreateAnAudioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio found by entered category Id - {0}..
        /// </summary>
        internal static string DeleteAudioHandlerCanNotFindAnAudioWithGivenCategoryIdError {
            get {
                return ResourceManager.GetString("DeleteAudioHandlerCanNotFindAnAudioWithGivenCategoryIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete an audio..
        /// </summary>
        internal static string DeleteAudioHandlerFailedToDeleteAnAudioError {
            get {
                return ResourceManager.GetString("DeleteAudioHandlerFailedToDeleteAnAudioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images found by entered category Id - {0}..
        /// </summary>
        internal static string DeleteImageHandlerCanNotFindAnImageWithGivenCategoryIdError {
            get {
                return ResourceManager.GetString("DeleteImageHandlerCanNotFindAnImageWithGivenCategoryIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete an image..
        /// </summary>
        internal static string DeleteImageHandlerFailedToDeleteAnImageError {
            get {
                return ResourceManager.GetString("DeleteImageHandlerFailedToDeleteAnImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no arts in the database..
        /// </summary>
        internal static string GetAllArtsHandlerCanNotFindAnyArtsError {
            get {
                return ResourceManager.GetString("GetAllArtsHandlerCanNotFindAnyArtsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no audios in the database..
        /// </summary>
        internal static string GetAllAudiosHandlerCanNotFindAnyAudioError {
            get {
                return ResourceManager.GetString("GetAllAudiosHandlerCanNotFindAnyAudioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no images in the database..
        /// </summary>
        internal static string GetAllImagesHandlerCanNotFindAnyImageError {
            get {
                return ResourceManager.GetString("GetAllImagesHandlerCanNotFindAnyImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no videos in the database..
        /// </summary>
        internal static string GetAllVideosHandlerCanNotFindAnyVideoError {
            get {
                return ResourceManager.GetString("GetAllVideosHandlerCanNotFindAnyVideoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arts found by entered Id - {0}..
        /// </summary>
        internal static string GetArtByIdHandlerCanNotFindArtWithGivenIdError {
            get {
                return ResourceManager.GetString("GetArtByIdHandlerCanNotFindArtWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arts found by entered streetcode Id - {0}..
        /// </summary>
        internal static string GetArtsByStreetcodeIdHandlerCanNotFindArtWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetArtsByStreetcodeIdHandlerCanNotFindArtWithGivenStreetcodeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio found by entered Id - {0}..
        /// </summary>
        internal static string GetAudioByIdHandlerCanNotFindAnAudioWithGivenIdError {
            get {
                return ResourceManager.GetString("GetAudioByIdHandlerCanNotFindAnAudioWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio found by entered streetcode Id - {0}..
        /// </summary>
        internal static string GetAudioByStreetcodeIdQueryHandlerCanNotFindAnAudioWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetAudioByStreetcodeIdQueryHandlerCanNotFindAnAudioWithGivenStreetcodeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio found by entered Id - {0}..
        /// </summary>
        internal static string GetBaseAudioHandlerCanNotFindAnAudioWithGivenIdError {
            get {
                return ResourceManager.GetString("GetBaseAudioHandlerCanNotFindAnAudioWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image found by entered Id - {0}..
        /// </summary>
        internal static string GetBaseImageHandlerCanNotFindAnAudioWithGivenIdError {
            get {
                return ResourceManager.GetString("GetBaseImageHandlerCanNotFindAnAudioWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image found by entered Id - {0}..
        /// </summary>
        internal static string GetImageByIdHandlerCanNotFindAnImageWithGivenIdError {
            get {
                return ResourceManager.GetString("GetImageByIdHandlerCanNotFindAnImageWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image found by entered streetcode Id - {0}..
        /// </summary>
        internal static string GetImageByStreetcodeIdHandlerCanNotFindAnImageWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetImageByStreetcodeIdHandlerCanNotFindAnImageWithGivenStreetcodeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No art found by entered streetcode Id - {0}..
        /// </summary>
        internal static string GetStreetcodeArtByStreetcodeIdHandlerCanNotFindAnArtWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetStreetcodeArtByStreetcodeIdHandlerCanNotFindAnArtWithGivenStreetcodeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video found by entered Id - {0}..
        /// </summary>
        internal static string GetVideoByIdHandlerCanNotFindAVideoWithGivenIdError {
            get {
                return ResourceManager.GetString("GetVideoByIdHandlerCanNotFindAVideoWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streetcode with id - {0} doesn`t exist..
        /// </summary>
        internal static string GetVideoByStreetcodeIdHandlerDoesntExistStreetcodeWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetVideoByStreetcodeIdHandlerDoesntExistStreetcodeWithGivenStreetcodeIdError", resourceCulture);
            }
        }
    }
}
