//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.MediatR.Newss {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewsErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.MediatR.Newss.NewsErrors", typeof(NewsErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date is required..
        /// </summary>
        internal static string CreateNewsCommandValidatorCreationDateIsRequiredError {
            get {
                return ResourceManager.GetString("CreateNewsCommandValidatorCreationDateIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is required..
        /// </summary>
        internal static string CreateNewsCommandValidatorTextIsRequiredError {
            get {
                return ResourceManager.GetString("CreateNewsCommandValidatorTextIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string CreateNewsCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("CreateNewsCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateNewsCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("CreateNewsCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required..
        /// </summary>
        internal static string CreateNewsCommandValidatorURLIsRequiredError {
            get {
                return ResourceManager.GetString("CreateNewsCommandValidatorURLIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL length should not be longer than {0} symbols..
        /// </summary>
        internal static string CreateNewsCommandValidatorURLMaxLengthError {
            get {
                return ResourceManager.GetString("CreateNewsCommandValidatorURLMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to news..
        /// </summary>
        internal static string CreateNewsHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("CreateNewsHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a news..
        /// </summary>
        internal static string CreateNewsHandlerFailedToCreateError {
            get {
                return ResourceManager.GetString("CreateNewsHandlerFailedToCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news found by entered Id - {0}..
        /// </summary>
        internal static string DeleteNewsHandlerCanNotFindNewsWithGivenIdError {
            get {
                return ResourceManager.GetString("DeleteNewsHandlerCanNotFindNewsWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete news..
        /// </summary>
        internal static string DeleteNewsHandlerFailedToDeleteError {
            get {
                return ResourceManager.GetString("DeleteNewsHandlerFailedToDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no news in the database..
        /// </summary>
        internal static string GetAllNewsHandlerCanNotFindAnyNewsError {
            get {
                return ResourceManager.GetString("GetAllNewsHandlerCanNotFindAnyNewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news by entered Url - {0}..
        /// </summary>
        internal static string GetNewsAndLinksByUrlHandlerCanNotFindANewsWithGivenURLError {
            get {
                return ResourceManager.GetString("GetNewsAndLinksByUrlHandlerCanNotFindANewsWithGivenURLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news by entered Id - {0}..
        /// </summary>
        internal static string GetNewsByIdHandlerCanNotFindANewWithGivenIdError {
            get {
                return ResourceManager.GetString("GetNewsByIdHandlerCanNotFindANewWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news by entered Url - {0}..
        /// </summary>
        internal static string GetNewsByUrlHandlerCanNotFindANewWithGivenURLError {
            get {
                return ResourceManager.GetString("GetNewsByUrlHandlerCanNotFindANewWithGivenURLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no news in the database..
        /// </summary>
        internal static string SortedByDateTimeHandlerCanNotFindAnyNewsError {
            get {
                return ResourceManager.GetString("SortedByDateTimeHandlerCanNotFindAnyNewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date is required..
        /// </summary>
        internal static string UpdateNewsCommandValidatorCreationDateIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateNewsCommandValidatorCreationDateIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is required..
        /// </summary>
        internal static string UpdateNewsCommandValidatorTextIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateNewsCommandValidatorTextIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string UpdateNewsCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateNewsCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateNewsCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateNewsCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required..
        /// </summary>
        internal static string UpdateNewsCommandValidatorURlIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateNewsCommandValidatorURlIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL length should not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateNewsCommandValidatorURlMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateNewsCommandValidatorURlMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to news..
        /// </summary>
        internal static string UpdateNewsHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("UpdateNewsHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update news..
        /// </summary>
        internal static string UpdateNewsHandlerFailedToUpdateError {
            get {
                return ResourceManager.GetString("UpdateNewsHandlerFailedToUpdateError", resourceCulture);
            }
        }
    }
}
