//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.MediatR.Partners {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartnersErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnersErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.MediatR.Partners.PartnersErrors", typeof(PartnersErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length must not be longer than {0} symbols..
        /// </summary>
        internal static string CreatePartnerCommandValidatorDescriptionMaxLengthError {
            get {
                return ResourceManager.GetString("CreatePartnerCommandValidatorDescriptionMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsKeyPartner is required..
        /// </summary>
        internal static string CreatePartnerCommandValidatorIsKeyPartnerIsRequiredError {
            get {
                return ResourceManager.GetString("CreatePartnerCommandValidatorIsKeyPartnerIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsVisibleEverywhere is required..
        /// </summary>
        internal static string CreatePartnerCommandValidatorIsVisibleEverywhereIsRequiredError {
            get {
                return ResourceManager.GetString("CreatePartnerCommandValidatorIsVisibleEverywhereIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogoId is required..
        /// </summary>
        internal static string CreatePartnerCommandValidatorLogoIdIsRequiredError {
            get {
                return ResourceManager.GetString("CreatePartnerCommandValidatorLogoIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetUrl length must not be longer than {0} symbols..
        /// </summary>
        internal static string CreatePartnerCommandValidatorTargetURLMaxLengthError {
            get {
                return ResourceManager.GetString("CreatePartnerCommandValidatorTargetURLMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string CreatePartnerCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("CreatePartnerCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length must not be longer than {0} symbols..
        /// </summary>
        internal static string CreatePartnerCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("CreatePartnerCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlTitle length must not be longer than {0} symbols..
        /// </summary>
        internal static string CreatePartnerCommandValidatorURLTitleMaxLengthError {
            get {
                return ResourceManager.GetString("CreatePartnerCommandValidatorURLTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No partner with such id..
        /// </summary>
        internal static string DeletePartnerHandlerNoPartnerWithGivenIdError {
            get {
                return ResourceManager.GetString("DeletePartnerHandlerNoPartnerWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partners..
        /// </summary>
        internal static string GetAllPartnersHandlerCanNotFindAnyPartnersError {
            get {
                return ResourceManager.GetString("GetAllPartnersHandlerCanNotFindAnyPartnersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partners..
        /// </summary>
        internal static string GetAllPartnerShortHandlerCanNotFindAnyPartnersError {
            get {
                return ResourceManager.GetString("GetAllPartnerShortHandlerCanNotFindAnyPartnersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partner with corresponding id: {0}..
        /// </summary>
        internal static string GetPartnerByIdHandlerCanNotFindnyPartnerWithGivenId {
            get {
                return ResourceManager.GetString("GetPartnerByIdHandlerCanNotFindnyPartnerWithGivenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partners with corresponding streetcode id: {0}.
        /// </summary>
        internal static string GetPartnersByStreetcodeIdHandlerCanNotFindAnyPartnersWithGivenStreetcodeId {
            get {
                return ResourceManager.GetString("GetPartnersByStreetcodeIdHandlerCanNotFindAnyPartnersWithGivenStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a partners by a streetcode id: {0}..
        /// </summary>
        internal static string GetPartnersByStreetcodeIdHandlerCanNotFindAPartnersWithGivenStreetcodeIdError {
            get {
                return ResourceManager.GetString("GetPartnersByStreetcodeIdHandlerCanNotFindAPartnersWithGivenStreetcodeIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length must not be longer than {0} symbols..
        /// </summary>
        internal static string UpdatePartnerCommandValidatorDescriptionMaxLengthError {
            get {
                return ResourceManager.GetString("UpdatePartnerCommandValidatorDescriptionMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsKeyPartner is required..
        /// </summary>
        internal static string UpdatePartnerCommandValidatorIsKeyPartnerIsRequired {
            get {
                return ResourceManager.GetString("UpdatePartnerCommandValidatorIsKeyPartnerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsVisibleEverywhere is required..
        /// </summary>
        internal static string UpdatePartnerCommandValidatorIsVisibleEverywhereIsRequiredError {
            get {
                return ResourceManager.GetString("UpdatePartnerCommandValidatorIsVisibleEverywhereIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogoId is required..
        /// </summary>
        internal static string UpdatePartnerCommandValidatorLogoIdIsRequiredError {
            get {
                return ResourceManager.GetString("UpdatePartnerCommandValidatorLogoIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetUrl length must not be longer than {0} symbols..
        /// </summary>
        internal static string UpdatePartnerCommandValidatorTargetURLMaxLengthError {
            get {
                return ResourceManager.GetString("UpdatePartnerCommandValidatorTargetURLMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string UpdatePartnerCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("UpdatePartnerCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length must not be longer than {0} symbols..
        /// </summary>
        internal static string UpdatePartnerCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("UpdatePartnerCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlTitle length must not be longer than {0} symbols..
        /// </summary>
        internal static string UpdatePartnerCommandValidatorURLTitleMaxLengthError {
            get {
                return ResourceManager.GetString("UpdatePartnerCommandValidatorURLTitleMaxLengthError", resourceCulture);
            }
        }
    }
}
