//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.MediatR.Team {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TeamErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.MediatR.Team.TeamErrors", typeof(TeamErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is required..
        /// </summary>
        internal static string CreatePositionCommandValidatorPositionIsRequiredError {
            get {
                return ResourceManager.GetString("CreatePositionCommandValidatorPositionIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position length must not be longer than {0} symbols..
        /// </summary>
        internal static string CreatePositionCommandValidatorPositionMaxLengthError {
            get {
                return ResourceManager.GetString("CreatePositionCommandValidatorPositionMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogoType is required..
        /// </summary>
        internal static string CreateTeamLinkCommandValidatorLogoTypeIsRequiredError {
            get {
                return ResourceManager.GetString("CreateTeamLinkCommandValidatorLogoTypeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetUrl is required..
        /// </summary>
        internal static string CreateTeamLinkCommandValidatorTargetUrlIsRequiredError {
            get {
                return ResourceManager.GetString("CreateTeamLinkCommandValidatorTargetUrlIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target url length must not be longer than {0} symbols..
        /// </summary>
        internal static string CreateTeamLinkCommandValidatorTargetUrlMaxLengthError {
            get {
                return ResourceManager.GetString("CreateTeamLinkCommandValidatorTargetUrlMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team member Id is required..
        /// </summary>
        internal static string CreateTeamLinkCommandValidatorTeamMemberIdIsRequiredError {
            get {
                return ResourceManager.GetString("CreateTeamLinkCommandValidatorTeamMemberIdIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to team link..
        /// </summary>
        internal static string CreateTeamLinkHandlerCannotConvertNullToTeamLinkError {
            get {
                return ResourceManager.GetString("CreateTeamLinkHandlerCannotConvertNullToTeamLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create team link..
        /// </summary>
        internal static string CreateTeamLinkHandlerCanNotCreateTeamLinkError {
            get {
                return ResourceManager.GetString("CreateTeamLinkHandlerCanNotCreateTeamLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a team..
        /// </summary>
        internal static string CreateTeamLinkHandlerFailedToCreateATeamError {
            get {
                return ResourceManager.GetString("CreateTeamLinkHandlerFailedToCreateATeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to map created team link..
        /// </summary>
        internal static string CreateTeamLinkHandlerFailedToMapCreatedTeamLinkError {
            get {
                return ResourceManager.GetString("CreateTeamLinkHandlerFailedToMapCreatedTeamLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no team in the database..
        /// </summary>
        internal static string GetAllMainTeamHandlerCanNotFindAnyTeamError {
            get {
                return ResourceManager.GetString("GetAllMainTeamHandlerCanNotFindAnyTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no positions in the database..
        /// </summary>
        internal static string GetAllPositionsHandlerCanNotFindAnyPositionsError {
            get {
                return ResourceManager.GetString("GetAllPositionsHandlerCanNotFindAnyPositionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no team in the database..
        /// </summary>
        internal static string GetAllTeamHandlerCanNotFindAnyTeamError {
            get {
                return ResourceManager.GetString("GetAllTeamHandlerCanNotFindAnyTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team links.
        /// </summary>
        internal static string GetAllTeamLinkHandlerCannotFindAnyTeamLinksError {
            get {
                return ResourceManager.GetString("GetAllTeamLinkHandlerCannotFindAnyTeamLinksError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No team by entered Id - {0}..
        /// </summary>
        internal static string GetByIdTeamHandlerCanNotFindATeamWithGivenIdError {
            get {
                return ResourceManager.GetString("GetByIdTeamHandlerCanNotFindATeamWithGivenIdError", resourceCulture);
            }
        }
    }
}
