//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.MediatR.Timeline {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimelineErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimelineErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.MediatR.Timeline.TimelineErrors", typeof(TimelineErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataViewPattern is required..
        /// </summary>
        internal static string CreateTimelineItemCommandValidatorDataViewPatternIsRequiredError {
            get {
                return ResourceManager.GetString("CreateTimelineItemCommandValidatorDataViewPatternIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required..
        /// </summary>
        internal static string CreateTimelineItemCommandValidatorDateIsRequiredError {
            get {
                return ResourceManager.GetString("CreateTimelineItemCommandValidatorDateIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length must not be longer than {0} symbols..
        /// </summary>
        internal static string CreateTimelineItemCommandValidatorDescriptionMaxLengthError {
            get {
                return ResourceManager.GetString("CreateTimelineItemCommandValidatorDescriptionMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string CreateTimelineItemCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("CreateTimelineItemCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length must not be longer than {0} symbols..
        /// </summary>
        internal static string CreateTimelineItemCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("CreateTimelineItemCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not convert null to timeline item..
        /// </summary>
        internal static string CreateTimelineItemHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("CreateTimelineItemHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a timeline item..
        /// </summary>
        internal static string CreateTimelineItemHandlerFailedToCreateError {
            get {
                return ResourceManager.GetString("CreateTimelineItemHandlerFailedToCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistoricalContexts is null..
        /// </summary>
        internal static string CreateTimelineItemHandlerHistoricalContextsIsNullError {
            get {
                return ResourceManager.GetString("CreateTimelineItemHandlerHistoricalContextsIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a timeline with corresponding id: {0}..
        /// </summary>
        internal static string DeleteTimelineItemHandlerCanNotFindWithIdError {
            get {
                return ResourceManager.GetString("DeleteTimelineItemHandlerCanNotFindWithIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a timeline..
        /// </summary>
        internal static string DeleteTimelineItemHandlerFailedToDeleteError {
            get {
                return ResourceManager.GetString("DeleteTimelineItemHandlerFailedToDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any timelineItem..
        /// </summary>
        internal static string GetAllTimelineItemsHandlerCanNotFindAnyError {
            get {
                return ResourceManager.GetString("GetAllTimelineItemsHandlerCanNotFindAnyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a timeline item with corresponding id: {0}..
        /// </summary>
        internal static string GetTimelineItemByIdHandlerCanNotFindWithGivenIdError {
            get {
                return ResourceManager.GetString("GetTimelineItemByIdHandlerCanNotFindWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any timeline item by the streetcode id: {0}..
        /// </summary>
        internal static string GetTimelineItemsByStreetcodeIdHandlerCanNotFindWithGivenIdError {
            get {
                return ResourceManager.GetString("GetTimelineItemsByStreetcodeIdHandlerCanNotFindWithGivenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataViewPattern is required..
        /// </summary>
        internal static string UpdateTimelineItemCommandValidatorDataViewPatternIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateTimelineItemCommandValidatorDataViewPatternIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required..
        /// </summary>
        internal static string UpdateTimelineItemCommandValidatorDateIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateTimelineItemCommandValidatorDateIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description length must not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateTimelineItemCommandValidatorDescriptionMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateTimelineItemCommandValidatorDescriptionMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string UpdateTimelineItemCommandValidatorTitleIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateTimelineItemCommandValidatorTitleIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length must not be longer than {0} symbols..
        /// </summary>
        internal static string UpdateTimelineItemCommandValidatorTitleMaxLengthError {
            get {
                return ResourceManager.GetString("UpdateTimelineItemCommandValidatorTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a timeline with corresponding id: {0}.
        /// </summary>
        internal static string UpdateTimelineItemHandlerCanNotFindWIthGIvenIdError {
            get {
                return ResourceManager.GetString("UpdateTimelineItemHandlerCanNotFindWIthGIvenIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update a timeline..
        /// </summary>
        internal static string UpdateTimelineItemHandlerFailedToUpdateError {
            get {
                return ResourceManager.GetString("UpdateTimelineItemHandlerFailedToUpdateError", resourceCulture);
            }
        }
    }
}
