//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.MediatR.AdditionalContent.Coordinate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoordinateErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoordinateErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.MediatR.AdditionalContent.Coordinate.CoordinateErrors", typeof(CoordinateErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is required field..
        /// </summary>
        internal static string CreateCoordinateCommandValidatorLatitudeIsRequiredError {
            get {
                return ResourceManager.GetString("CreateCoordinateCommandValidatorLatitudeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude should be in range from -90 to 90.
        /// </summary>
        internal static string CreateCoordinateCommandValidatorLatitudeRange {
            get {
                return ResourceManager.GetString("CreateCoordinateCommandValidatorLatitudeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longtitude is required field..
        /// </summary>
        internal static string CreateCoordinateCommandValidatorLongtitudeIsRequiredError {
            get {
                return ResourceManager.GetString("CreateCoordinateCommandValidatorLongtitudeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longtitude should be in range from -180 to 180.
        /// </summary>
        internal static string CreateCoordinateCommandValidatorLongtitudeRange {
            get {
                return ResourceManager.GetString("CreateCoordinateCommandValidatorLongtitudeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to streetcodeCoordinate..
        /// </summary>
        internal static string CreateCoordinateHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("CreateCoordinateHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a streetcodeCoordinate..
        /// </summary>
        internal static string CreateCoordinateHandlerCreateFailedError {
            get {
                return ResourceManager.GetString("CreateCoordinateHandlerCreateFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a coordinate..
        /// </summary>
        internal static string DeleteCoordinateHandlerDeleteFailedError {
            get {
                return ResourceManager.GetString("DeleteCoordinateHandlerDeleteFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinate with corresponding categoryId: {0}.
        /// </summary>
        internal static string DeleteCoordinateHandlerNotFoundByIdError {
            get {
                return ResourceManager.GetString("DeleteCoordinateHandlerNotFoundByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinates by a streetcode id: {0}..
        /// </summary>
        internal static string GetCoordinatesByStreetcodeIdHandlerCanNotFindCoordinatesByStreetcodeId {
            get {
                return ResourceManager.GetString("GetCoordinatesByStreetcodeIdHandlerCanNotFindCoordinatesByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinates by a streetcode id: {0}, because such streetcode doesn`t exist..
        /// </summary>
        internal static string GetCoordinatesByStreetcodeIdHandlerCanNotFindCoordinatesStreetcodeNotExist {
            get {
                return ResourceManager.GetString("GetCoordinatesByStreetcodeIdHandlerCanNotFindCoordinatesStreetcodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to streetcodeCoordinate..
        /// </summary>
        internal static string UpdateCoordinateHandlerCanNotConvertFromNullError {
            get {
                return ResourceManager.GetString("UpdateCoordinateHandlerCanNotConvertFromNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is required field..
        /// </summary>
        internal static string UpdateCoordinateHandlerLatitudeIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateCoordinateHandlerLatitudeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longtitude is required field..
        /// </summary>
        internal static string UpdateCoordinateHandlerLongtitudeIsRequiredError {
            get {
                return ResourceManager.GetString("UpdateCoordinateHandlerLongtitudeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update a streetcodeCoordinate..
        /// </summary>
        internal static string UpdateCoordinateHandlerUpdateFailureError {
            get {
                return ResourceManager.GetString("UpdateCoordinateHandlerUpdateFailureError", resourceCulture);
            }
        }
    }
}
